apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: andresiqq/serverfiles:v1.6
        ports:
        - containerPort: 3000
        env:
        - name: DBUSER_NAME
          valueFrom:
            secretKeyRef:
              name: mongodatabase-secret
              key: mongodatabase-user
        - name: DBUSER_PWD
          valueFrom:
            secretKeyRef:
              name: mongodatabase-secret
              key: mongodatabase-password 
        - name: DB_URLPATH
          valueFrom:
            configMapKeyRef:
              name: mongodatabase-config
              key: mongodatabase-urlpath
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30447